# Sklearn

## sklearn.cross_validation

документация: http://scikit-learn.org/stable/modules/cross_validation.html

In [1]:
from sklearn import cross_validation, datasets

import numpy as np

C:\Users\rurum\AppData\Local\Continuum\Anaconda2\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


### Разовое разбиение данных на обучение и тест с помощью train_test_split

In [15]:
iris = datasets.load_iris()

In [22]:
train_data, test_data, train_labels, test_labels = cross_validation.train_test_split(iris.data, iris.target, 
                                                                                     test_size = 0.3)

In [20]:
#убедимся, что тестовая выборка действительно составляет 0.3 от всех данных
float(len(test_labels))/len(iris.data)

0.3

In [21]:
print 'Размер обучающей выборки: {} объектов \nРазмер тестовой выборки: {} объектов'.format(len(train_data),
                                                                                            len(test_data))

Размер обучающей выборки: 105 объектов 
Размер тестовой выборки: 45 объектов


In [23]:
print 'Обучающая выборка:\n', train_data[:5]
print '\n'
print 'Тестовая выборка:\n', test_data[:5]

Обучающая выборка:
[[ 6.2  2.9  4.3  1.3]
 [ 5.8  2.7  5.1  1.9]
 [ 6.3  3.4  5.6  2.4]
 [ 6.1  2.6  5.6  1.4]
 [ 4.7  3.2  1.3  0.2]]


Тестовая выборка:
[[ 6.9  3.1  5.1  2.3]
 [ 5.8  4.   1.2  0.2]
 [ 7.9  3.8  6.4  2. ]
 [ 5.2  4.1  1.5  0.1]
 [ 5.8  2.7  3.9  1.2]]


In [26]:
print 'Метки классов на обучающей выборке:\n', len(train_labels)
print '\n'
print 'Метки классов на тестовой выборке:\n', len(test_labels)

Метки классов на обучающей выборке:
105


Метки классов на тестовой выборке:
45


### Стратегии проведения кросс-валидации

#### KFold

In [31]:
for train_indices, test_indices in cross_validation.KFold(10, n_folds = 10):
    print train_indices, test_indices

[1 2 3 4 5 6 7 8 9] [0]
[0 2 3 4 5 6 7 8 9] [1]
[0 1 3 4 5 6 7 8 9] [2]
[0 1 2 4 5 6 7 8 9] [3]
[0 1 2 3 5 6 7 8 9] [4]
[0 1 2 3 4 6 7 8 9] [5]
[0 1 2 3 4 5 7 8 9] [6]
[0 1 2 3 4 5 6 8 9] [7]
[0 1 2 3 4 5 6 7 9] [8]
[0 1 2 3 4 5 6 7 8] [9]


In [48]:
for train_indices, test_indices in cross_validation.KFold(10, n_folds =3, shuffle = True):
    print train_indices, test_indices

[1 4 5 6 7 9] [0 2 3 8]
[0 1 2 3 4 6 8] [5 7 9]
[0 2 3 5 7 8 9] [1 4 6]


In [59]:
for train_indices, test_indices in cross_validation.KFold(10, n_folds = 10, shuffle = True, random_state = 1):
    print train_indices, test_indices

[0 1 3 4 5 6 7 8 9] [2]
[0 1 2 3 4 5 6 7 8] [9]
[0 1 2 3 4 5 7 8 9] [6]
[0 1 2 3 5 6 7 8 9] [4]
[1 2 3 4 5 6 7 8 9] [0]
[0 1 2 4 5 6 7 8 9] [3]
[0 2 3 4 5 6 7 8 9] [1]
[0 1 2 3 4 5 6 8 9] [7]
[0 1 2 3 4 5 6 7 9] [8]
[0 1 2 3 4 6 7 8 9] [5]


#### StratifiedKFold

In [61]:
target = np.array([0] * 5 + [1] * 5)
print target
for train_indices, test_indices in cross_validation.StratifiedKFold(target, n_folds = 3, shuffle = True, random_state = 0):
    print train_indices, test_indices

[0 0 0 0 0 1 1 1 1 1]
[1 3 4 6 8 9] [0 2 5 7]
[0 2 4 5 7 8] [1 3 6 9]
[0 1 2 3 5 6 7 9] [4 8]


In [74]:
target = np.array([0, 1] * 5)
print target
for train_indices, test_indices in cross_validation.StratifiedKFold(target, n_folds = 2,shuffle = True):
    print train_indices, test_indices

[0 1 0 1 0 1 0 1 0 1]
[2 5 6 7] [0 1 3 4 8 9]
[0 1 3 4 8 9] [2 5 6 7]


#### ShuffleSplit

In [109]:
#?cross_validation.ShuffleSplit()
c=0
for train_indices, test_indices in cross_validation.ShuffleSplit(50, n_iter = 10, test_size = 7):
    c=c+1
    print train_indices, test_indices
print c

[16 26 32  2 38  4 15  5 35 25 20  1  9  7  0 22  8 33 23 43 48 29 19  3 21
 40 42 41 47 17 46 24 30 12 18 36 37 14 11 27 31 49 13] [39 10 45 34  6 28 44]
[27 28 38  4 19 26  1 13 18 31 30 49  5  7 21 23 40 34 20 22 32 41 10 17 44
  3 47  0 29 15 46 43  2 36 39 24 45 14 35 12 25 16 33] [48 42  6  8  9 37 11]
[31 24 45 40 44 49 12  6 21 32 23  9 16 37  5 33 42 35 34 17 46 28 29 15  4
  0 25 27 10 43 36  8 20 11  3 18 38  2 22 41 26 19  7] [ 1 30 14 47 39 13 48]
[27 19 49 10 36  4 31 34 20 45 17  2 18 39 26 48 25  3 40 12 44 42 16 38 46
 24  1 33 21 37  7  9  8 14 43 28 15 47  5 32 23  0 41] [29  6 30 22 11 35 13]
[44 47 20 31 42 24 39  6  7 26 19 16  4  1 43 28 30 34 41 18 17 29 14 13 23
 12  2 33  3 36 11 27  0 40 38  8 10 46 22 15  9 45 25] [37 21 32  5 48 35 49]
[28 40 16 37 25 36 34 41 17 47 26  3 12 43 48 10 35 13 49 21 31  1 22 33 24
 30  4 29 20  8  9 44  6  5 38  7 45 42 27 18 15  2 14] [23  0 11 19 46 39 32]
[ 8 44  0 23 16 14 20 45 37 32 26 10 33 35 25 29 41  5  4 30  9 12 19 

#### StratifiedShuffleSplit

In [69]:
target = np.array([0] * 5 + [1] * 5)
print target
for train_indices, test_indices in cross_validation.StratifiedShuffleSplit(target, n_iter = 4, test_size = 0.2):
    print train_indices, test_indices

[0 0 0 0 0 1 1 1 1 1]
[9 1 4 0 7 2 6 5] [8 3]
[0 8 7 5 2 3 9 4] [6 1]
[3 1 7 5 0 2 8 9] [6 4]
[4 2 7 5 9 0 1 8] [6 3]


#### Leave-One-Out

In [100]:
for train_indices, test_index in cross_validation.LeaveOneOut(10):
    print train_indices, test_index

[1 2 3 4 5 6 7 8 9] [0]
[0 2 3 4 5 6 7 8 9] [1]
[0 1 3 4 5 6 7 8 9] [2]
[0 1 2 4 5 6 7 8 9] [3]
[0 1 2 3 5 6 7 8 9] [4]
[0 1 2 3 4 6 7 8 9] [5]
[0 1 2 3 4 5 7 8 9] [6]
[0 1 2 3 4 5 6 8 9] [7]
[0 1 2 3 4 5 6 7 9] [8]
[0 1 2 3 4 5 6 7 8] [9]


Больше стратегий проведения кросс-валидации доступно здесь: http://scikit-learn.org/stable/modules/cross_validation.html#cross-validation-iterators